security:
    encoders:
      Blog\ModelBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    providers:
        users:
            entity: { class: ModelBundle:User}


    firewalls:

        admin_area:

            pattern: ^/.*

            form_login:
                login_path: admin_user_login
                check_path: admin_user_check
                default_target_path: admin_setting
                username_parameter: _email
                remember_me: true

            logout:
                path: admin_user_logout
                target: admin_user_login

            remember_me:
                key: MiPassphrase
                lifetime: 1800
                path: /.*
                domain: ~
            security: true
            anonymous: ~


        front_area:
            pattern: ^/
            anonymous: ~

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/settings, roles: ROLE_USER }
        - { path: ^/settings/users*, roles: ROLE_ADMIN }
