security:
    encoders:
      Blog\ModelBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    providers:
        users:
            entity: { class: ModelBundle:User}


    firewalls:

        admin_area:

            pattern: ^/.*

            form_login:
                login_path: admin_user_login
                check_path: admin_user_check
                default_target_path: admin_profile
                username_parameter: _email
                remember_me: true

            logout:
                path: admin_user_logout
                target: admin_user_login

            remember_me:
                key: random-key-2014
            security: true
            anonymous: ~

        front_area:
            pattern: ^/
            anonymous: ~

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/user/edit*, roles: ROLE_USER }
        - { path: ^/admin/user/delete*, roles: ROLE_USER }
        - { path: ^/admin/users*, roles: ROLE_ADMIN }
        - { path: ^/admin, roles: ROLE_USER }
