parameters:
    author_manager.class: Blog\ModelBundle\Services\AuthorManager
    post_manager.class: Blog\ModelBundle\Services\PostManager
    user_manager.class: Blog\ModelBundle\Services\UserManager

services:
    author_manager:
        class: %author_manager.class%
        arguments:
            - @doctrine.orm.entity_manager

    post_manager:
        class: %post_manager.class%
        arguments:
            - @doctrine.orm.entity_manager
            - @form.factory

    user_manager:
            class: %user_manager.class%
            arguments:
                - @doctrine.orm.entity_manager