parameters:
    author_manager.class: Blog\ModelBundle\Services\AuthorManager
    post_manager.class:   Blog\ModelBundle\Services\PostManager
    user_manager.class:   Blog\ModelBundle\Services\UserManager
    comment_manager.class:   Blog\ModelBundle\Services\CommentManager
    logout_handler.class: Blog\ModelBundle\Services\LogoutHandler

    is_active.class:     Blog\ModelBundle\Twig\Helpers\isActive
    get_user_id.class:   Blog\ModelBundle\Twig\Helpers\getUserId
    show_form_errors.class:   Blog\ModelBundle\Twig\Helpers\showFormErrors

    form_errors.class:   Blog\ModelBundle\Form\Helpers\FormError

services:
    logout_handler:
        class: %logout_handler.class%
        arguments:
          - @security.context
          - @doctrine.orm.entity_manager

    author_manager:
        class: %author_manager.class%
        arguments:
            - @doctrine.orm.entity_manager

    post_manager:
        class: %post_manager.class%
        arguments:
            - @doctrine.orm.entity_manager
            - @form.factory

    user_manager:
            class: %user_manager.class%
            arguments:
                - @doctrine.orm.entity_manager

    comment_manager:
            class: %comment_manager.class%
            arguments:
                - @doctrine.orm.entity_manager

    form_errors:
            class: %form_errors.class%

    isActive.twig.helper:
        class: %is_active.class%
        tags:
            - { name: twig.extension }

    fieldError.twig.helper:
        class: %show_form_errors.class%
        tags:
            - { name: twig.extension }

    getUserId.twig.helper:
            class: %get_user_id.class%
            tags:
                - { name: twig.extension }