admin_author_show:
    pattern: /admin/author/{slug}
    defaults: { _controller: AdminBundle:Author:show }


admin_post:
    pattern: /admin/post
    defaults: { _controller: AdminBundle:Post:index }

admin_post_show:
    pattern: /admin/post/{slug}
    defaults: { _controller: AdminBundle:Post:show }

admin_post_edit:
    pattern: /admin/post/edit/{id}
    defaults: { _controller: AdminBundle:Post:edit }

admin_post_new:
    pattern: /admin/post/new
    defaults: { _controller: AdminBundle:Post:new }

admin_post_create_comment:
  pattern: /admin/{slug}/create-comment
  defaults: { _controller: AdminBundle:Post:createComment }


admin_setting:
    pattern:  /settings
    defaults: { _controller: AdminBundle:Settings:index }




admin_users:
    pattern:  /settings/users
    defaults: { _controller: AdminBundle:Settings:users }

admin_user_edit:
    pattern:  /settings/user/edit/{id}
    defaults: { _controller: AdminBundle:Settings:edit }

admin_user_delete:
  pattern:  /settings/user/delete/{id}
  defaults: { _controller: AdminBundle:Settings:delete }



admin_security_login:
  pattern:  /admin/login
  defaults: { _controller: AdminBundle:Security:login }

admin_security_login_check:
  pattern:  /admin/loginCheck
  defaults: { _controller: AdminBundle:Security:loginCheck }

admin_security_logout:
  pattern:  /admin/logout
  defaults: { _controller: AdminBundle:Security:logout }

admin_security_register:
    pattern:  /admin/register
    defaults: { _controller: AdminBundle:Security:register }

admin_security_forgot:
    pattern:  /admin/forgot
    defaults: { _controller: AdminBundle:Security:forgot }
