#Admin Index
admin_admin:
    pattern:  /admin
    defaults: { _controller: AdminBundle:Index:index }

########################################################


#Admin Author
admin_author_show:
    pattern: /admin/author/{slug}
    defaults: { _controller: AdminBundle:Author:show }

########################################################


#Admin Post
admin_post:
    pattern: /admin/post
    defaults: { _controller: AdminBundle:Post:index }

admin_post_show:
    pattern: /admin/post/show-{slug}
    defaults: { _controller: AdminBundle:Post:show }

admin_post_delete:
    pattern: /admin/post/delete/{id}
    defaults: { _controller: AdminBundle:Post:delete }

admin_post_edit:
    pattern: /admin/post/edit/{id}
    defaults: { _controller: AdminBundle:Post:edit }

admin_post_new:
    pattern: /admin/post/new
    defaults: { _controller: AdminBundle:Post:new }

admin_post_create_comment:
  pattern: /admin/{slug}/create-comment
  defaults: { _controller: AdminBundle:Post:createComment }

########################################################


#Admin User
admin_user:
    pattern:  /admin/users
    defaults: { _controller: AdminBundle:User:users }

admin_user_edit:
    pattern:  /admin/user/edit/{id}
    defaults: { _controller: AdminBundle:User:edit }

admin_user_delete:
  pattern:  /admin/user/delete/{id}
  defaults: { _controller: AdminBundle:User:delete }

admin_user_create:
  pattern:  /admin/user/create
  defaults: { _controller: AdminBundle:User:create }

########################################################


#Admin Login
admin_user_login:
  pattern:  /login
  defaults: { _controller: AdminBundle:Login:login }

admin_user_check:
  pattern:  /loginCheck
  defaults: { _controller: AdminBundle:Login:loginCheck }

admin_user_logout:
  pattern:  /logout
  defaults: { _controller: AdminBundle:Login:logout }

########################################################


#Admin Register
admin_user_register:
    pattern:  /register
    defaults: { _controller: AdminBundle:Register:register }

admin_user_forgot:
    pattern:  /forgot
    defaults: { _controller: AdminBundle:Forgot:forgot }

########################################################