admin_homepage:
    pattern:  /index
    defaults: { _controller: BlogAdminBundle:Index:index }

admin_login:
    pattern:  /login
    defaults: { _controller: BlogAdminBundle:Index:login }

admin_signout:
    pattern:  /signout
    defaults: { _controller: BlogAdminBundle:Index:signOut }

admin_register:
    pattern:  /register
    defaults: { _controller: BlogAdminBundle:Index:register }

admin_forgot:
    pattern:  /forgot
    defaults: { _controller: BlogAdminBundle:Index:forgot }



admin_author_show:
    pattern: /author/{slug}
    defaults: { _controller: BlogAdminBundle:Author:show }


admin_post:
    pattern: /post
    defaults: { _controller: BlogAdminBundle:Post:index }

admin_post_show:
    pattern: /post/{slug}
    defaults: { _controller: BlogAdminBundle:Post:show }

admin_post_edit:
    pattern: /post/edit/{id}
    defaults: { _controller: BlogAdminBundle:Post:edit }

admin_post_new:
    pattern: /post/new
    defaults: { _controller: BlogAdminBundle:Post:new }




admin_setting:
    pattern:  /settings
    defaults: { _controller: BlogAdminBundle:Settings:index }




admin_users:
    pattern:  /settings/users
    defaults: { _controller: BlogAdminBundle:Settings:users }

admin_user_edit:
    pattern:  /settings/user/edit/{id}
    defaults: { _controller: BlogAdminBundle:Settings:edit }

admin_user_delete:
  pattern:  /settings/user/delete/{id}
  defaults: { _controller: BlogAdminBundle:Settings:delete }