parameters:
#    blog_admin.example.class: Blog\AdminBundle\Example

services:
#    blog_admin.example:
#        class: %blog_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
