<?php

namespace Blog\ModelBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRepository extends EntityRepository
{
    public function getAllRoles()
    {
        $roles = $this->getEntityManager()->getRepository('ModelBundle:Role')->findAll();


        return $roles;
    }
}