front_posts:
    pattern: /posts
    defaults: { _controller: FrontBundle:Posts:index }

front_posts_show:
    pattern: /posts/{slug}.{_format}
    defaults: { _controller: FrontBundle:Posts:show, _format: html }
    requirements:
            _format: html|json

front_post_create_comment:
  pattern: /posts/{slug}/create-comment
  defaults: { _controller: FrontBundle:Posts:createComment }

front_author_show:
    pattern: /author/{slug}.{_format}
    defaults: { _controller: FrontBundle:Author:show, _format: html }
    requirements:
        _format: html|json